import { useEffect, useRef, useState, type ChangeEvent } from "react";
import { ArrowDown, ChevronLeft, ChevronRight, Disc3, Instagram, Menu, Pause, Play, SkipBack, SkipForward, Volume2, VolumeX, X, Youtube } from "lucide-react";

const A="/media/";
const tracks=[
 {title:"Chain, Engine 'N Thunder", file:"01-chain-engine-n-thunder.mp3", tag:"METAL PUNK DEATH SQUAD", mood:"Chrome & fire", dur:"03:39"},
 {title:"Chrome in the blood, Broken 'N Chains", file:"02-chrome-blood-broken-chains.mp3", tag:"METAL PUNK DEATH SQUAD", mood:"No brakes", dur:"04:20"},
 {title:"Feed the machine", file:"03-feed-the-machine.mp3", tag:"METAL PUNK DEATH SQUAD", mood:"Steel pulse", dur:"03:31"},
 {title:"Motör Speed 'N' Roll", file:"04-motor-speed-n-roll.mp3", tag:"METAL PUNK DEATH SQUAD", mood:"Ignition", dur:"02:44"},
 {title:"Raising the speed", file:"05-raising-the-speed.mp3", tag:"METAL PUNK DEATH SQUAD", mood:"Full throttle", dur:"05:11"},
 {title:"Ride to Live, Live to Ride", file:"06-ride-to-live.mp3", tag:"METAL PUNK DEATH SQUAD", mood:"Open road", dur:"04:53"},
 {title:"We don't sucks anything", file:"07-we-dont-sucks-anything.mp3", tag:"METAL PUNK DEATH SQUAD", mood:"Raw & loud", dur:"02:53"},
 {title:"Wrecking the machine (another v)", file:"08-wrecking-machine-another-v.mp3", tag:"METAL PUNK DEATH SQUAD", mood:"Afterburner", dur:"04:54"},
 {title:"Wrecking the machine", file:"09-wrecking-the-machine.mp3", tag:"METAL PUNK DEATH SQUAD", mood:"Riot mode", dur:"04:56"},
];

function formatTime(s:number){ if(!Number.isFinite(s)) return "00:00"; return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(Math.floor(s%60)).padStart(2,"0")}`; }

export default function Home(){
 const [current,setCurrent]=useState(0); const [playing,setPlaying]=useState(false); const [muted,setMuted]=useState(false); const [progress,setProgress]=useState(0); const [menu,setMenu]=useState(false);
 const audio=useRef<HTMLAudioElement>(null);
 const visualizerCanvas=useRef<HTMLCanvasElement>(null); const audioContext=useRef<AudioContext|null>(null); const analyser=useRef<AnalyserNode|null>(null); const sourceConnected=useRef(false); const animationFrame=useRef<number|undefined>(undefined);
 const track=tracks[current];
 useEffect(()=>{ const el=audio.current; if(!el) return; el.load(); if(playing) el.play().catch(()=>setPlaying(false)); },[current]);
 useEffect(()=>{ const el=audio.current; if(!el) return; const onTime=()=>setProgress(el.duration?el.currentTime/el.duration:0); const onEnd=()=>{setCurrent((current+1)%tracks.length); setPlaying(true)}; el.addEventListener("timeupdate",onTime); el.addEventListener("ended",onEnd); return()=>{el.removeEventListener("timeupdate",onTime);el.removeEventListener("ended",onEnd)} },[current]);
 useEffect(()=>{ const canvas=visualizerCanvas.current; const el=audio.current; if(!canvas||!el) return; const ctx=canvas.getContext("2d"); if(!ctx) return; const resize=()=>{const dpr=window.devicePixelRatio||1; canvas.width=canvas.clientWidth*dpr; canvas.height=canvas.clientHeight*dpr; ctx.setTransform(dpr,0,0,dpr,0,0)}; resize(); window.addEventListener("resize",resize); const draw=()=>{const w=canvas.clientWidth,h=canvas.clientHeight; ctx.clearRect(0,0,w,h); const data=analyser.current?new Uint8Array(analyser.current.frequencyBinCount):null; if(data) analyser.current?.getByteFrequencyData(data); const bars=46; for(let i=0;i<bars;i++){const v=data?(data[i%data.length]/255):(.18+.1*Math.sin(Date.now()/260+i)); const bh=10+v*h*.72; const x=i*(w/bars)+2; ctx.fillStyle=i%5===0?"rgba(231,255,82,.78)":"rgba(200,66,47,.62)"; ctx.fillRect(x,h-bh,w/bars-4,bh)} animationFrame.current=requestAnimationFrame(draw)}; draw(); return()=>{window.removeEventListener("resize",resize); if(animationFrame.current) cancelAnimationFrame(animationFrame.current)} },[current]);
 const toggle=()=>{ const el=audio.current; if(!el) return; if(playing){el.pause();setPlaying(false)}else{try{if(!audioContext.current){audioContext.current=new AudioContext(); analyser.current=audioContext.current.createAnalyser(); analyser.current.fftSize=128; const source=audioContext.current.createMediaElementSource(el); source.connect(analyser.current); analyser.current.connect(audioContext.current.destination); sourceConnected.current=true} audioContext.current.resume()}catch{} el.play().then(()=>setPlaying(true)).catch(()=>{})} };
 const select=(i:number)=>{setCurrent(i);setPlaying(true); document.getElementById("music")?.scrollIntoView({behavior:"smooth"})};
 const previous=()=>select((current-1+tracks.length)%tracks.length); const next=()=>select((current+1)%tracks.length);
 const seek=(e:ChangeEvent<HTMLInputElement>)=>{ const v=Number(e.target.value); setProgress(v); if(audio.current?.duration) audio.current.currentTime=v*audio.current.duration };
 return <div className="site-shell">
  <audio key={track.file} ref={audio} crossOrigin="anonymous" src={A+encodeURIComponent(track.file)} muted={muted} preload="auto" playsInline onCanPlay={()=>{if(playing) audio.current?.play().catch(()=>setPlaying(false))}} />
  <div className="grain"/><div className="red-beam"/>
  <header className="topbar"><a className="wordmark" href="#top">S<span>R</span></a><nav className={menu?"nav open":"nav"}>{["THE ALBUM","THE SOUND","TRACKLIST","CONTACT"].map((x,i)=><a key={x} href={["#top","#sound","#music","#footer"][i]} onClick={()=>setMenu(false)}><b>0{i+1}</b>{x}</a>)}</nav><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button><a className="header-cta" href="#music">LISTEN NOW <ChevronRight size={16}/></a></header>
  <main id="top">
   <section className="hero fullscreen-hero">
    <div className="hero-full-image"/><div className="hero-full-vignette"/><canvas ref={visualizerCanvas} className="hero-visualizer" aria-label="Audio visualizer"/>
    <div className="hero-topline"><span>SR / 001</span><b>METAL PUNK DEATH SQUAD</b><span>EST. 2026</span></div>
    <div className="hero-logo"><img src={A+"speedrizer-logo.png"} alt="Speedrizër"/></div>
    <div className="hero-full-copy"><p className="eyebrow"><span className="pulse-dot"/> {playing?"LIVE SIGNAL / NOW PLAYING":"NEW ALBUM / FULL-LENGTH"}</p><h1>Motör Speed<br/><em>'N' Roll</em></h1><p>{track.title} <span>•</span> {track.tag}</p><div className="hero-actions"><button className="primary-btn" onClick={toggle}>{playing?<Pause size={19} fill="currentColor"/>:<Play size={19} fill="currentColor"/>}{playing?"PAUSE SIGNAL":"PLAY THE ALBUM"}</button><a className="ghost-btn" href="#music">VIEW TRACKLIST <ArrowDown size={16}/></a></div></div>
    <div className="hero-full-meta"><span>01 / 09</span><i/><span>FULL-SCREEN ARTWORK<br/>LIVE AUDIO REACTIVITY</span></div><div className="hero-index">01 <span>/</span> 04</div>
   </section>
   <section id="sound" className="manifesto"><div className="manifesto-number">01</div><div className="manifesto-content"><p className="eyebrow">THE SOUND OF SPEEDRIZËR</p><h2>Born to<br/><span>overdrive.</span></h2><p>Motorik riffs. Rusted amplifiers. A drum kit that refuses to slow down. This is not background music — it is a machine with the throttle pinned.</p><div className="signal-row"><span>120–190 BPM</span><i/><span>ANALOG HEAT</span><i/><span>ZERO BRAKES</span></div></div><div className="manifesto-visual"><div className="waveform">{Array.from({length:34},(_,i)=><i key={i} style={{height:`${18+((i*37)%68)}%`}}/> )}</div><span className="visual-caption">SIGNAL / 001</span></div></section>
   <section id="music" className="music-section"><div className="section-head"><div><p className="eyebrow">THE FULL THROTTLE</p><h2>TRACK<span>LIST</span></h2></div><div className="album-meta"><Disc3 size={17}/><span>9 TRACKS<br/><b>2026 / SR-001</b></span></div></div><div className="track-grid">{tracks.map((t,i)=><button style={{animationDelay:`${i*55}ms`}} className={`track ${i===current?"active":""}`} key={t.title} onClick={()=>select(i)}><span className="track-no">{String(i+1).padStart(2,"0")}</span><span className="track-thumb"><img src={A+"cover.jpg"} alt=""/></span><span className="track-main"><strong>{t.title}</strong><small>{t.tag} <em>•</em> {t.mood}</small></span><span className="track-dur">{i===current&&playing?<span className="mini-bars"><i/><i/><i/></span>:t.dur}</span><span className="track-play">{i===current&&playing?<Pause size={14} fill="currentColor"/>:<Play size={14} fill="currentColor"/>}</span></button>)}</div></section>
   <section className="statement"><div className="statement-bg">SPEED</div><p className="eyebrow">A RECORD FOR THE RIDE HOME</p><h2>Keep the engine<br/><span>alive.</span></h2><a className="primary-btn" href="#music">ENTER THE MACHINE <ChevronRight size={18}/></a></section>
  </main>
  <footer id="footer" className="footer"><div className="footer-brand">SPEEDRIZËR<span>®</span></div><div className="footer-links"><a href="#top">BACK TO TOP ↑</a><a href="#music">MUSIC</a><a href="#sound">THE SOUND</a></div><div className="footer-social"><a href="#footer"><Instagram size={17}/></a><a href="#footer"><Youtube size={17}/></a><span>© 2026 SPEEDRIZËR</span></div></footer>
  <div className="player"><div className="player-track"><div className="player-cover"><img src={A+"cover.jpg"}/></div><div><span>NOW PLAYING</span><strong>{track.title}</strong></div></div><button className="player-skip" onClick={previous} aria-label="Previous track"><SkipBack size={16} fill="currentColor"/></button><button className="player-toggle" onClick={toggle} aria-label={playing?"Pause audio":"Play audio"}>{playing?<Pause size={20} fill="currentColor"/>:<Play size={20} fill="currentColor"/>}</button><button className="player-skip" onClick={next} aria-label="Next track"><SkipForward size={16} fill="currentColor"/></button><div className="player-progress"><div className="time-line"><span>{formatTime((audio.current?.duration||0)*progress)}</span><input aria-label="Seek" type="range" min="0" max="1" step="0.001" value={progress} onChange={seek}/><span>{track.dur}</span></div></div><button className="mute" onClick={()=>setMuted(!muted)} aria-label="Mute">{muted?<VolumeX size={17}/>:<Volume2 size={17}/>}</button></div>
 </div>
}
